### ISSUE TITLE
SP Metadata cannot be generated without a config XML file in place

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-sso#87] opened 2021-10-25 09:22 UTC
The module expects a config file to exist, and falls back to the default file in `.sso/config` from the skeleton project, which doesn't necessarily exist on all installations.

Steps to reproduce:
1. Remove the `.config/sso/saml-idp-metadata.xml` file
2. Try to generate the SP metadata XML by visiting `https://site/sso/metadata`

You should see the SP metadata XML file generated, but right now it errors out with `Invalid SSO settings. Contact your administrator.`

The solution would be to move the default file to the module directory to ensure it always exists, and load it from there, and remove it from the skeleton project.

Related to support request: https://humanmade.zendesk.com/agent/tickets/5673

**Comment by roborourke** [comment] 2021-11-02 12:55
Closing out as the docs were updated in #89 - it seems it's intended behaviour to require the config XML in order to generate the metadata.

**Closed by roborourke** 2021-11-02 12:55 UTC
Labels: bug
